// <auto-generated />
using ConAppEFCode1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConAppEFCode1.Migrations
{
    [DbContext(typeof(OrganizationContext))]
    [Migration("20241226064611_orgDb")]
    partial class orgDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConAppEFCode1.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DeptId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ConAppEFCode1.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeEmpId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint");

                    b.Property<int>("WorkDeptId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("EmployeeEmpId");

                    b.HasIndex("WorkDeptId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ConAppEFCode1.Models.Employee", b =>
                {
                    b.HasOne("ConAppEFCode1.Models.Employee", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeEmpId");

                    b.HasOne("ConAppEFCode1.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("WorkDeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ConAppEFCode1.Models.Employee", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
